server:
  port: 8081 #-- ???????? ?? ????????? preprod
  address: localhost #-- ???????? ?? ????????? preprod

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.liquibase.parameters.postgres-db.name}?createDatabaseIfNotExist=true #-- ???????? ?? ????????? preprod
    username: postgres #-- ???????? ?? preprod user
    password: admin #-- ?????? ?????? ? vault
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${spring.liquibase.parameters.postgres-db.schema}
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false
      ddl-auto: none
  rabbitmq:
    host: localhost #-- ???????? ?? ????????? preprod
    port: 5672 #-- ???????? ?? ????????? preprod
    username: guest #-- ???????? ?? preprod user
    password: guest #-- ?????? ?????? ? vault
    queue: api_and_exec_ctrl
    exchange: iot_sim
    routing_key: command_to_execution_controller
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    parameters:
      postgres-db:
        name: iotsim_db
        schema: IOT_SIM
        owner: ${spring.datasource.username}
        encoding: UTF-8
        lc-collate: Russian_Russia.1251
        lc-ctype: Russian_Russia.1251
        tablespace: pg_default
        connection-limit: -1

token:
  signing:
    key: k1gFkf7fxntESE71nV6L7AZ1YktPiEsdixYufaZDpfkVDEt1e6CHdblGkomqWeLe #-- ?????? ? vault

minio:
  access_key: admin #-- ???????? ?? preprod user
  secret_key: password #-- ?????? ?????? ? vault
  url: http://localhost:9000 #-- ???????? ?? ????????? preprod
  bucket_name: iotsim #-- ???????? ?? ????????? preprod

logging:
  file:
    name: logs/application.log #-- ???????? ?? ????????? preprod
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  level:
    root: DEBUG
